# pubspec.yaml

name: agilizaiapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.1
  pinput: ^5.0.1
  http: ^1.2.1
  flutter_secure_storage: ^9.2.2
  qr_flutter: ^4.1.0
  provider: ^6.1.2
  intl: ^0.20.2
  image_picker: ^1.0.0
  table_calendar: ^3.1.2
  shared_preferences: ^2.2.3
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
 

# --- Seção 'flutter' ---
flutter:
  uses-material-design: true
  generate: true

  # Apenas a pasta 'images' agora
  assets: # <<< Este 'assets:' é para o empacotamento do Flutter
    - assets/images/ # <<< APENAS ESTA LINHA AGORA

# --- Configuração do FLUTTER_GEN (para gerar assets.gen.dart) ---
# Esta seção informa ao flutter_gen_runner quais pastas escanear e como.
flutter_gen:
  # Onde os arquivos gerados serão salvos (padrão é lib/gen/)
  # output: lib/gen/
  
  # A lista de assets para o FLUTTER_GEN ESCANEAR.
  # Apenas a pasta 'images' agora
  assets: # <<< ESTE É O 'assets:' para o FlutterGen
    - assets/images/ # <<< APENAS ESTA LINHA AGORA
  
  integrations:
    flutter_svg: false
    lottie: false
    rive: false